<?php

declare(strict_types=1);

/*
 * This file is part of rekalogika/mapper package.
 *
 * (c) Priyadi Iman Nurcahyo <https://rekalogika.dev>
 *
 * For the full copyright and license information, please view the LICENSE file
 * that was distributed with this source code.
 */

namespace Rekalogika\Mapper\Transformer\Proxy\Implementation;

use Rekalogika\Mapper\Transformer\ObjectToObjectMetadata\ObjectToObjectMetadata;
use Rekalogika\Mapper\Transformer\Proxy\Exception\ProxyNotSupportedException;
use Rekalogika\Mapper\Transformer\Proxy\ProxyGeneratorInterface;
use Rekalogika\Mapper\Transformer\Proxy\ProxySpecification;
use Symfony\Component\VarExporter\Exception\LogicException;
use Symfony\Component\VarExporter\ProxyHelper;

final class ProxyGenerator implements ProxyGeneratorInterface
{
    public function generateTargetProxy(ObjectToObjectMetadata $metadata): ProxySpecification
    {
        $sourceClass = $metadata->getSourceClass();
        $targetClass = $metadata->getTargetClass();

        /** @var class-string */
        $proxyClass = $this->generateProxyClassName($sourceClass, $targetClass);

        try {
            $proxyCode = $this->generateProxyCode($sourceClass, $targetClass);
        } catch (LogicException $e) {
            throw new ProxyNotSupportedException($metadata, $e);
        }

        return new ProxySpecification($proxyClass, $proxyCode);
    }

    /**
     * @param class-string $sourceClass
     * @param class-string $targetClass
     * @return string
     */
    private function generateProxyClassName(string $sourceClass, string $targetClass): string
    {
        return sprintf(
            'Rekalogika\Mapper\Generated\%s\To\%s',
            $sourceClass,
            $targetClass
        );
    }

    /**
     * @param class-string $sourceClass
     * @param class-string $targetClass
     * @return string
     */
    private function generateProxyCode(string $sourceClass, string $targetClass): string
    {
        $proxyClass = $this->generateProxyClassName($sourceClass, $targetClass);
        $targetReflection = new \ReflectionClass($targetClass);

        // get proxy class name & namespace
        $shortName = preg_replace('/.*\\\\/', '', $proxyClass);
        $namespace = preg_replace('/\\\\[^\\\\]*$/', '', $proxyClass);

        return
            $this->getClassHeader() .
            sprintf('namespace %s;', $namespace) . "\n\n" .
            sprintf(
                'final %sclass %s%s',
                $targetReflection->isReadOnly() ? 'readonly ' : ' ',
                $shortName,
                ProxyHelper::generateLazyGhost($targetReflection)
            );
    }

    private function getClassHeader(): string
    {
        return <<<'PHP'
<?php

declare(strict_types=1);

/*
 * This is a proxy class automatically generated by the rekalogika/mapper
 * package. Do not edit it manually.
 */


PHP;
    }
}
