#!/usr/bin/env php
<?php

declare(strict_types=1);

/*
 * This file is part of rekalogika/mapper package.
 *
 * (c) Priyadi Iman Nurcahyo <https://rekalogika.dev>
 *
 * For the full copyright and license information, please view the LICENSE file
 * that was distributed with this source code.
 */

namespace Rekalogika\Mapper\Tests;

require_once __DIR__ . '/../vendor/autoload.php';

use Rekalogika\Mapper\Tests\Common\MapperTestFactory;

$factory = new MapperTestFactory();
$application = $factory->getApplication()->run();
