<?php

// This file is automatically generated by the rekalogika/mapper PHPStan
// integration. Any changes made to this file will be lost when the file is
// regenerated. If you need, you may define additional mappings in a separate
// file alongside this file.
//
// This file is used to generate pre-warmed mapping metadata for Mapper. It can
// improve performance especially on read-only deployments, but not strictly
// required for normal operation of Mapper. Mapper should be able to work
// normally without pre-warmed metadata.

use Rekalogika\Mapper\CacheWarmer\MappingCollection;

return function (MappingCollection $mappingCollection) : void {
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MethodMapperTest.php on line 33
        source: \Brick\Money\Money::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MethodMapper\MoneyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/CustomTransformerTest.php on line 27
        source: \Brick\Money\Money::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Money\MoneyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectMapperTest.php on line 48
        source: \Brick\Money\Money::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\MoneyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectMapperTest.php on line 79
        source: \Brick\Money\Money::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\MoneyDtoForProxy::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectMapperTest.php on line 121
        source: \Brick\Money\Money::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\MoneyDtoForTargetInvalidTypeHint::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectMapperTest.php on line 94
        source: \Brick\Money\Money::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\MoneyDtoForTargetModification::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectMapperTest.php on line 107
        source: \Brick\Money\Money::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\MoneyDtoForTargetReplacement::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectMapperTest.php on line 68
        source: \Brick\Money\Money::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\MoneyDtoInterface::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/AdderTest.php on lines 46, 55
        source: \Rekalogika\Mapper\Tests\Fixtures\Adder\Comment::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\AdderDto\CommentDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/AdderTest.php on line 103
        source: \Rekalogika\Mapper\Tests\Fixtures\Adder\ImmutablePost::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\AdderDto\ImmutablePostDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/AdderTest.php on lines 34, 73
        source: \Rekalogika\Mapper\Tests\Fixtures\Adder\Post::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\AdderDto\PostDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ArrayAndObjectMappingTest.php on line 104
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayAndObject\ContainsArray::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayAndObject\AnotherContainsArray::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ArrayAndObjectMappingTest.php on lines 33, 51, 67, 86
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayAndObject\ContainsArray::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayAndObject\ContainsObject::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ArrayAndObjectMappingTest.php on line 26
        // tests/src/IntegrationTest/DataCollectorTest.php on line 32
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayAndObject\ContainsObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayAndObject\ContainsArray::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on lines 153, 336
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithArrayProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayAccessPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line 203
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithArrayProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayInterfacePropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on lines 239, 349
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithArrayProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line 52
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithArrayProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayPropertyWithoutTypeHintDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ArrayGetterSetterTest.php on line 28
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithArrayProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArraySetterDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line 254
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithArrayProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithCollectionPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToTraversableMappingTest.php on line 59
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithArrayProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithTraversablePropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToTraversableMappingTest.php on line 116
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithArrayProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithTraversablePropertyWithoutTypeHintDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ArrayGetterSetterTest.php on line 60
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithArrayProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithVariadicArrayConstructorDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ArrayGetterSetterTest.php on line 44
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithArrayProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithVariadicArraySetterDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line 368
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithArrayPropertyWithStringKey::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayPropertyDtoWithIntKey::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line 171
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithCollectionProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayAccessPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line 221
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithCollectionProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayInterfacePropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToTraversableMappingTest.php on line 79
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithLazyDoctrineCollectionProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithTraversablePropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToTraversableMappingTest.php on line 95
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithLazyDoctrineCollectionWithPresetCountableProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithTraversablePropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line 189
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithNullCollectionProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithNotNullArrayAccessPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToTraversableMappingTest.php on line 134
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithNullCollectionProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithNotNullTraversablePropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line 276
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithSplObjectStorageProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayAccessPropertyWithObjectKeyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line 294
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithSplObjectStorageProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on lines 102, 307, 391
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithTraversableProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayAccessPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on lines 116, 321
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithTraversableProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line 82
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithTraversableProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayPropertyWithCompatibleHintDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line 67
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithTraversableProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayPropertyWithoutTypeHintDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line 432
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithTraversableProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayWithGetterNoSetterDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line 131
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithTraversableProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithCollectionPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line 408
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithTraversableProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithCollectionWithGetterNoSetterDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToTraversableMappingTest.php on line 39
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithTraversableProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithTraversablePropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/AttributeTest.php on line 42
        source: \Rekalogika\Mapper\Tests\Fixtures\Attribute\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Attribute\SomeObjectWithInvalidPropertyAttribute::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/BasicMappingTest.php on line 34
        // tests/src/IntegrationTest/IterableMapperTest.php on line 24
        source: \Rekalogika\Mapper\Tests\Fixtures\Basic\Person::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Basic\PersonDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/BasicMappingTest.php on line 43
        source: \Rekalogika\Mapper\Tests\Fixtures\Basic\Person::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Basic\PersonWithoutAgeDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/BasicMappingTest.php on line 75
        source: \Rekalogika\Mapper\Tests\Fixtures\Basic\PersonWithDogDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Basic\PersonWithDog::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/BasicMappingTest.php on line 103
        source: \Rekalogika\Mapper\Tests\Fixtures\Basic\PersonWithDogDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Basic\PersonWithImmutableDogWithoutSetter::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/BasicMappingTest.php on line 51
        source: \Rekalogika\Mapper\Tests\Fixtures\Basic\PersonWithoutAge::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Basic\PersonDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ConstructorAndPropertyTest.php on line 77
        source: \Rekalogika\Mapper\Tests\Fixtures\ConstructorAndProperty\SourceObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ConstructorAndProperty\ObjectWithConstructorAndSetter::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ConstructorAndPropertyTest.php on line 32
        source: \Rekalogika\Mapper\Tests\Fixtures\ConstructorAndProperty\SourceObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ConstructorAndProperty\ObjectWithConstructorArgumentsAndGetters::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ConstructorAndPropertyTest.php on line 64
        source: \Rekalogika\Mapper\Tests\Fixtures\ConstructorAndProperty\SourceObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ConstructorAndProperty\ObjectWithConstructorArgumentsAndPublicProperties::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ConstructorAndPropertyTest.php on line 48
        source: \Rekalogika\Mapper\Tests\Fixtures\ConstructorAndProperty\SourceObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ConstructorAndProperty\ObjectWithIdOnlyOnConstructor::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DateTimeMappingTest.php on line 195
        source: \Rekalogika\Mapper\Tests\Fixtures\DateTime\DateTimeTestObjectInterface::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\DateTime\DateTimeTestObjectInterface::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DateTimeMappingTest.php on line 160
        source: \Rekalogika\Mapper\Tests\Fixtures\DateTime\ObjectWithDateTimeCollection::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\DateTime\ObjectWithDateTimeCollectionDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DateTimeMappingTest.php on lines 93, 112
        source: \Rekalogika\Mapper\Tests\Fixtures\DateTime\OldObjectWithDateTime::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\DateTime\OldObjectWithDateTimeDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DateTimeMappingTest.php on line 130
        source: \Rekalogika\Mapper\Tests\Fixtures\DateTime\OldObjectWithDateTime::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\DateTime\OldObjectWithDateTimeWithTimeZoneDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DoctrineTest.php on line 82
        source: \Rekalogika\Mapper\Tests\Fixtures\Doctrine\EntityWithSingleIdentifier::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Doctrine\EntityWithSingleIdentifierDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DoctrineTest.php on line 112
        source: \Rekalogika\Mapper\Tests\Fixtures\Doctrine\SimpleEntityInputDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Doctrine\SimpleEntity::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DynamicPropertyTest.php on line 237
        source: \Rekalogika\Mapper\Tests\Fixtures\DynamicProperty\ObjectExtendingStdClass::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\DynamicProperty\AnotherObjectExtendingStdClass::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DynamicPropertyTest.php on line 304
        source: \Rekalogika\Mapper\Tests\Fixtures\DynamicProperty\ObjectExtendingStdClass::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\DynamicProperty\ObjectWithNonNullPropertyThatCannotBeCastFromNull::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DynamicPropertyTest.php on line 120
        source: \Rekalogika\Mapper\Tests\Fixtures\DynamicProperty\ObjectExtendingStdClass::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ScalarDto\ObjectWithScalarPropertiesDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DynamicPropertyTest.php on line 182
        source: \Rekalogika\Mapper\Tests\Fixtures\DynamicProperty\ObjectExtendingStdClassWithExplicitScalarProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ScalarDto\ObjectWithScalarPropertiesDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DynamicPropertyTest.php on line 312
        source: \Rekalogika\Mapper\Tests\Fixtures\DynamicProperty\ObjectWithNullProperty::class,
        target: \stdClass::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectEnumStringMappingTest.php on line 57
        source: \Rekalogika\Mapper\Tests\Fixtures\EnumAndStringable\ObjectWithEnumProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\EnumAndStringable\ObjectWithStringProperty::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectEnumStringMappingTest.php on line 49
        source: \Rekalogika\Mapper\Tests\Fixtures\EnumAndStringable\ObjectWithNumericStringableProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\EnumAndStringableDto\ObjectWithFloatPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectEnumStringMappingTest.php on line 41
        source: \Rekalogika\Mapper\Tests\Fixtures\EnumAndStringable\ObjectWithNumericStringableProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\EnumAndStringableDto\ObjectWithIntegerPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectEnumStringMappingTest.php on lines 66, 77, 86
        source: \Rekalogika\Mapper\Tests\Fixtures\EnumAndStringable\ObjectWithStringProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\EnumAndStringable\ObjectWithEnumProperty::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectEnumStringMappingTest.php on line 33
        source: \Rekalogika\Mapper\Tests\Fixtures\EnumAndStringable\ObjectWithStringableProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\EnumAndStringableDto\ObjectWithStringPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ExtraTargetValuesTest.php on lines 28, 68
        source: \Rekalogika\Mapper\Tests\Fixtures\ExtraTargetValues\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ExtraTargetValues\SomeObjectWithConstructorDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ExtraTargetValuesTest.php on line 47
        source: \Rekalogika\Mapper\Tests\Fixtures\ExtraTargetValues\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ExtraTargetValues\SomeObjectWithPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/InheritanceReversedTest.php on line 29
        source: \Rekalogika\Mapper\Tests\Fixtures\InheritanceDto\ConcreteClassADto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Inheritance\AbstractClass::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/InheritanceTest.php on line 33
        source: \Rekalogika\Mapper\Tests\Fixtures\Inheritance\ConcreteClassA::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\InheritanceDto\AbstractClassDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/InheritanceTest.php on line 46
        source: \Rekalogika\Mapper\Tests\Fixtures\Inheritance\ConcreteClassA::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\InheritanceDto\AbstractClassWithoutMapDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/InheritanceTest.php on line 59
        source: \Rekalogika\Mapper\Tests\Fixtures\Inheritance\ConcreteClassA::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\InheritanceDto\InterfaceDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/InheritanceTest.php on line 71
        source: \Rekalogika\Mapper\Tests\Fixtures\Inheritance\ConcreteClassA::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\InheritanceDto\InterfaceWithoutMapDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/InheritanceTest.php on line 53
        source: \Rekalogika\Mapper\Tests\Fixtures\Inheritance\ConcreteClassC::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\InheritanceDto\AbstractClassDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/InheritanceTest.php on line 78
        source: \Rekalogika\Mapper\Tests\Fixtures\Inheritance\ConcreteClassC::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\InheritanceDto\InterfaceDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/InternalClassTest.php on line 27
        source: \Rekalogika\Mapper\Tests\Fixtures\InternalClass\ObjectWithInternalClass::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\InternalClass\ObjectWithInternalClassDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/Issue232Test.php on line 27
        source: \Rekalogika\Mapper\Tests\Fixtures\Issue232\BigDecimalSource::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Issue232\BigDecimalTarget::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/Issue232Test.php on line 35
        source: \Rekalogika\Mapper\Tests\Fixtures\Issue232\CurrencySource::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Issue232\CurrencyTarget::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/LazyObjectTest.php on lines 99, 109
        source: \Rekalogika\Mapper\Tests\Fixtures\LazyObject\ObjectWithId::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\LazyObject\ChildObjectWithIdDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/LazyObjectTest.php on lines 37, 46
        source: \Rekalogika\Mapper\Tests\Fixtures\LazyObject\ObjectWithId::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\LazyObject\ObjectWithIdDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/LazyObjectTest.php on line 65
        source: \Rekalogika\Mapper\Tests\Fixtures\LazyObject\ObjectWithId::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\LazyObject\ObjectWithIdEagerDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/LazyObjectTest.php on line 56
        source: \Rekalogika\Mapper\Tests\Fixtures\LazyObject\ObjectWithId::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\LazyObject\ObjectWithIdFinalDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/LazyObjectTest.php on line 81
        source: \Rekalogika\Mapper\Tests\Fixtures\LazyObject\ObjectWithId::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\LazyObject\ObjectWithIdReadOnlyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/LazyObjectTest.php on line 119
        source: \Rekalogika\Mapper\Tests\Fixtures\LazyObject\ObjectWithIdAndName::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\LazyObject\ObjectWithIdAndNameInConstructorDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/LazyObjectTest.php on line 135
        source: \Rekalogika\Mapper\Tests\Fixtures\LazyObject\ObjectWithIdAndName::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\LazyObject\ObjectWithIdInConstructorDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MagicTest.php on line 26
        source: \Rekalogika\Mapper\Tests\Fixtures\Magic\ObjectWithMagicGet::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Magic\SomeDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MagicTest.php on line 36
        source: \Rekalogika\Mapper\Tests\Fixtures\Magic\SomeDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Magic\ObjectWithMagicSet::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapAttributeTest.php on lines 95, 115
        source: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\OtherObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObjectDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapAttributeTest.php on line 55
        source: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\ObjectExtendingSomeObjectDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapAttributeTest.php on line 75
        source: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\ObjectOverridingSomeObjectDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapAttributeTest.php on line 35
        source: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObjectDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapAttributeTest.php on line 161
        source: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObjectSkippingMappingDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapAttributeTest.php on line 144
        source: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObjectWithInvalidTargetDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapAttributeTest.php on line 151
        source: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObjectWithSamePropertyNameDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapAttributeTest.php on line 135
        source: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObjectWithUnpromotedConstructorDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapAttributeTest.php on line 125
        source: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObjectDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\ObjectExtendingOtherObject::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapAttributeTest.php on line 105
        source: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObjectDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\OtherObject::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapAttributeTest.php on lines 45, 65, 85
        source: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObjectDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObject::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapAttributeTest.php on line 171
        source: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObjectSkippingMapping::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapAttribute\SomeObjectWithSamePropertyNameDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapPropertyPathTest.php on line 297
        source: \Rekalogika\Mapper\Tests\Fixtures\MapPropertyPathDto\BookDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapPropertyPath\Book::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapPropertyPathTest.php on line 311
        source: \Rekalogika\Mapper\Tests\Fixtures\MapPropertyPath\Book::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapPropertyPathDto\Book2Dto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapPropertyPathTest.php on line 265
        source: \Rekalogika\Mapper\Tests\Fixtures\MapPropertyPath\Book::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapPropertyPathDto\BookDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapPropertyPathTest.php on line 349
        source: \Rekalogika\Mapper\Tests\Fixtures\MapPropertyPath\Chapter::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapPropertyPathDto\Chapter2Dto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MethodMapperTest.php on line 43
        source: \Rekalogika\Mapper\Tests\Fixtures\MethodMapper\MoneyDto::class,
        target: \Brick\Money\Money::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MethodMapperTest.php on line 118
        source: \Rekalogika\Mapper\Tests\Fixtures\MethodMapper\ObjectWithCollectionProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MethodMapper\ObjectWithArrayPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MethodMapperTest.php on line 54
        source: \Rekalogika\Mapper\Tests\Fixtures\MethodMapper\ObjectWithObjectWithScalarProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MethodMapper\ObjectWithObjectWithScalarPropertiesDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MethodMapperTest.php on line 91
        source: \Rekalogika\Mapper\Tests\Fixtures\MethodMapper\ObjectWithObjectWithScalarPropertiesDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MethodMapper\ObjectWithObjectWithScalarProperties::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MixedTypeTest.php on line 26
        source: \Rekalogika\Mapper\Tests\Fixtures\MixedType\ObjectWithMixedProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MixedType\ObjectWithMixedPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MixedTypeTest.php on line 33
        source: \Rekalogika\Mapper\Tests\Fixtures\MixedType\ObjectWithMixedProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MixedType\ObjectWithUntypedPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/CustomTransformerTest.php on line 36
        source: \Rekalogika\Mapper\Tests\Fixtures\Money\MoneyDto::class,
        target: \Brick\Money\Money::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/CustomTransformerTest.php on line 47
        source: \Rekalogika\Mapper\Tests\Fixtures\Money\ObjectWithIntegerBackedMoneyProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Money\ObjectWithMoneyAmountDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/CustomTransformerTest.php on line 60
        source: \Rekalogika\Mapper\Tests\Fixtures\Money\ObjectWithMoneyAmountDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Money\ObjectWithIntegerBackedMoneyProperty::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectKeysTest.php on line 27
        source: \Rekalogika\Mapper\Tests\Fixtures\ObjectKeys\RelationshipMap::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectKeysDto\RelationshipMapDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectMapperTest.php on line 167
        source: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\Baz::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\Foo::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectMapperTest.php on line 157
        source: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\Foo::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\Baz::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectMapperTest.php on line 58
        source: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\MoneyDto::class,
        target: \Brick\Money\Money::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectMapperTest.php on line 151
        source: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\Person::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\FinalPersonDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectMapperTest.php on line 127
        source: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\Person::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\PersonDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectWithExistingValueTest.php on lines 34, 52
        source: \Rekalogika\Mapper\Tests\Fixtures\ObjectWithExistingValueDto\RootObjectDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectWithExistingValue\RootObject::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectWithExistingValueTest.php on line 68
        source: \Rekalogika\Mapper\Tests\Fixtures\ObjectWithExistingValueDto\RootObjectWithoutSetterDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectWithExistingValue\RootObject::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TransformerOverrideTest.php on line 28
        source: \Rekalogika\Mapper\Tests\Fixtures\Override\ObjectWithArrayProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Override\ObjectWithArrayPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/PropertyInSetterAndConstructorTest.php on lines 31, 45
        source: \Rekalogika\Mapper\Tests\Fixtures\PropertyInSetterAndConstructor\ParentObjectDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\PropertyInSetterAndConstructor\ParentObject::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/PropertyMappingTest.php on line 244
        source: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\Bar::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\Baz::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/PropertyMappingTest.php on line 199
        source: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\ChildOfSomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\ChildOfSomeObjectDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/PropertyMappingTest.php on line 182
        source: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\ChildOfSomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\SomeObjectDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/PropertyMappingTest.php on line 241
        source: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\Foo::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\Baz::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/PropertyMappingTest.php on line 216
        source: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\ChildOfSomeObjectDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/PropertyMappingTest.php on line 271
        source: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\ObjectWithChild1::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/PropertyMappingTest.php on line 284
        source: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\ObjectWithChild2::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/PropertyMappingTest.php on line 165
        source: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\SomeObjectDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/PropertyMappingTest.php on line 233
        source: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\SomeObjectWithConstructorDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/PropertyMappingTest.php on line 297
        source: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\SomeObjectWithDateTimeImmutableDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ReadOnlyTest.php on line 27
        source: \Rekalogika\Mapper\Tests\Fixtures\ReadOnly\Source::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ReadOnly\FinalReadOnlyObjectDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ReadOnlyTest.php on line 39
        source: \Rekalogika\Mapper\Tests\Fixtures\ReadOnly\Source::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ReadOnly\ReadOnlyObjectDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RecursionTest.php on line 64
        source: \Rekalogika\Mapper\Tests\Fixtures\Recursive\ObjectWithRefToItself::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\RecursiveDto\ObjectWithRefToItselfDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RecursionTest.php on line 34
        source: \Rekalogika\Mapper\Tests\Fixtures\Recursive\ParentObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\RecursiveDto\ParentObjectDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line 148
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithAdderRemover::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line 195
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithAdderRemoverWithAllowDeleteAttachedToGetter::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line 217
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithAdderRemoverWithAllowDeleteAttachedToRemover::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on lines 56, 80
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArray::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line 124
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayWithoutAllowDeleteAttribute::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line 171
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithImmutableAdderRemover::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line 239
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDtoWithAllowTargetDeleteAttribute::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithAdderRemover::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line 102
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDtoWithAllowTargetDeleteAttribute::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArray::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line 261
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDtoWithAllowTargetDeleteAttributeAttachedToGetter::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithAdderRemover::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ConstructorTest.php on line 65
        source: \Rekalogika\Mapper\Tests\Fixtures\Scalar\ObjectWithScalarProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Constructor\ObjectWithConstructorAndExtraMandatoryArgumentDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ConstructorTest.php on line 53
        source: \Rekalogika\Mapper\Tests\Fixtures\Scalar\ObjectWithScalarProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Constructor\ObjectWithConstructorAndPropertiesDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ConstructorTest.php on line 34
        source: \Rekalogika\Mapper\Tests\Fixtures\Scalar\ObjectWithScalarProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Constructor\ObjectWithConstructorDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ConstructorTest.php on line 72
        source: \Rekalogika\Mapper\Tests\Fixtures\Scalar\ObjectWithScalarProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Constructor\ObjectWithConstructorWithExtraOptionalArgumentDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ConstructorTest.php on line 46
        source: \Rekalogika\Mapper\Tests\Fixtures\Scalar\ObjectWithScalarProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Constructor\ObjectWithPrivateConstructorDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DynamicPropertyTest.php on line 209
        source: \Rekalogika\Mapper\Tests\Fixtures\Scalar\ObjectWithScalarProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\DynamicProperty\ObjectExtendingStdClass::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ScalarToScalar/ScalarPropertiesMappingTestCase.php on line 97
        source: \Rekalogika\Mapper\Tests\Fixtures\Scalar\ObjectWithScalarProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ScalarDto\ObjectWithBoolPropertiesDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ScalarToScalar/ScalarPropertiesMappingTestCase.php on line 108
        source: \Rekalogika\Mapper\Tests\Fixtures\Scalar\ObjectWithScalarProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ScalarDto\ObjectWithFloatPropertiesDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ScalarToScalar/ScalarPropertiesMappingTestCase.php on line 75
        source: \Rekalogika\Mapper\Tests\Fixtures\Scalar\ObjectWithScalarProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ScalarDto\ObjectWithIntPropertiesDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ScalarToScalar/ScalarPropertiesMappingTestCase.php on line 42
        source: \Rekalogika\Mapper\Tests\Fixtures\Scalar\ObjectWithScalarProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ScalarDto\ObjectWithScalarConstructorArgumentDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/LazyObjectTest.php on lines 154, 164
        // tests/src/IntegrationTest/ScalarToScalar/ScalarPropertiesMappingTestCase.php on line 31
        source: \Rekalogika\Mapper\Tests\Fixtures\Scalar\ObjectWithScalarProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ScalarDto\ObjectWithScalarPropertiesDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ScalarToScalar/ScalarPropertiesMappingTestCase.php on line 86
        source: \Rekalogika\Mapper\Tests\Fixtures\Scalar\ObjectWithScalarProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ScalarDto\ObjectWithStringPropertiesDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DynamicPropertyTest.php on line 196
        source: \Rekalogika\Mapper\Tests\Fixtures\Scalar\ObjectWithScalarProperties::class,
        target: \stdClass::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ConstructorTest.php on line 103
        source: \Rekalogika\Mapper\Tests\Fixtures\Scalar\ObjectWithScalarPropertiesAndAdditionalNullProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Constructor\ObjectWithConstructorAndExtraMandatoryArgumentDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ScalarToScalar/ScalarPropertiesMappingTestCase.php on line 64
        source: \Rekalogika\Mapper\Tests\Fixtures\Scalar\ObjectWithScalarPropertiesWithNullContents::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ScalarDto\ObjectWithScalarConstructorArgumentDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ScalarToScalar/ScalarPropertiesMappingTestCase.php on line 53
        source: \Rekalogika\Mapper\Tests\Fixtures\Scalar\ObjectWithScalarPropertiesWithNullContents::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ScalarDto\ObjectWithScalarPropertiesDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/UidTest.php on line 39
        source: \Rekalogika\Mapper\Tests\Fixtures\Uid\ObjectWithStringUids::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\UidDto\ObjectWithUidsDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/UidTest.php on line 29
        source: \Rekalogika\Mapper\Tests\Fixtures\Uid\ObjectWithUids::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\UidDto\ObjectWithStringUidsDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/UidTest.php on line 50
        source: \Rekalogika\Mapper\Tests\Fixtures\Uid\ObjectWithUids::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\UidDto\ObjectWithUidsDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/UninitializedPropertyTest.php on line 39
        source: \Rekalogika\Mapper\Tests\Fixtures\UninitializedProperty\ObjectWithInitializedProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\UninitializedPropertyDto\FinalObjectWithInitializedPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/UninitializedPropertyTest.php on line 55
        source: \Rekalogika\Mapper\Tests\Fixtures\UninitializedProperty\ObjectWithInitializedProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\UninitializedPropertyDto\FinalObjectWithUninitializedPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/UninitializedPropertyTest.php on line 31
        source: \Rekalogika\Mapper\Tests\Fixtures\UninitializedProperty\ObjectWithInitializedProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\UninitializedPropertyDto\ObjectWithInitializedPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/UninitializedPropertyTest.php on line 47
        source: \Rekalogika\Mapper\Tests\Fixtures\UninitializedProperty\ObjectWithInitializedProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\UninitializedPropertyDto\ObjectWithUninitializedPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/UninitializedPropertyTest.php on line 73
        source: \Rekalogika\Mapper\Tests\Fixtures\UninitializedProperty\ObjectWithUninitializedProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\UninitializedPropertyDto\FinalObjectWithInitializedPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/UninitializedPropertyTest.php on line 91
        source: \Rekalogika\Mapper\Tests\Fixtures\UninitializedProperty\ObjectWithUninitializedProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\UninitializedPropertyDto\FinalObjectWithUninitializedPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/UninitializedPropertyTest.php on line 65
        source: \Rekalogika\Mapper\Tests\Fixtures\UninitializedProperty\ObjectWithUninitializedProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\UninitializedPropertyDto\ObjectWithInitializedPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/UninitializedPropertyTest.php on line 82
        source: \Rekalogika\Mapper\Tests\Fixtures\UninitializedProperty\ObjectWithUninitializedProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\UninitializedPropertyDto\ObjectWithUninitializedPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/WitherMethodTest.php on line 35
        source: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObjectWithObjectWithFluentSetter::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/WitherMethodTest.php on lines 71, 101
        source: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObjectWithObjectWithImmutableSetter::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/WitherMethodTest.php on line 59
        source: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObjectWithObjectWithSetterReturningForeignObject::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/WitherMethodTest.php on line 47
        source: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObjectWithObjectWithVoidSetter::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/WitherMethodTest.php on line 83
        source: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObjectWithObjectWithWither::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/WitherMethodTest.php on line 95
        source: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObjectWithoutSetterDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ConstructorTest.php on line 84
        source: \stdClass::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Constructor\ObjectWithConstructorDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ConstructorTest.php on line 96
        source: \stdClass::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Constructor\ObjectWithMandatoryConstructorThatCannotBeCastFromNullDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DynamicPropertyTest.php on line 260
        source: \stdClass::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\DynamicProperty\ObjectExtendingStdClassWithProperties::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DynamicPropertyTest.php on lines 99, 138, 150, 168
        source: \stdClass::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ScalarDto\ObjectWithScalarPropertiesDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DynamicPropertyTest.php on lines 279, 292
        source: \stdClass::class,
        target: \stdClass::class
    );
    
    // Mapper was unable to detect the types of the following mappings. Most of
    // the time, this is harmless and not an error, and should not affect the
    // normal operation of Mapper.
    
    // source: unknown
    // target: unknown
    // occurrences:
    // tests/src/Common/IterableMapperDecorator.php on line 29
    // tests/src/Common/MapperDecorator.php on line 37
    // tests/src/IntegrationTest/DateTimeMappingTest.php on line 62
    // tests/src/Services/RememberingMapper/RememberingMapper.php on line 51
};