<?php

// This file is automatically generated by the rekalogika/mapper package.
// Any changes made to this file will be lost when the file is regenerated.
// You may add additional mappings in a separate file alongside this file.

use Rekalogika\Mapper\Cache\MappingCollection;

return function (MappingCollection $mappingCollection) : void {
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectMapperTest.php on line: 109
        source: \Brick\Money\Money::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\MoneyDtoForTargetInvalidTypeHint::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectMapperTest.php on line: 82
        source: \Brick\Money\Money::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\MoneyDtoForTargetModification::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectMapperTest.php on line: 95
        source: \Brick\Money\Money::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\MoneyDtoForTargetReplacement::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/AdderTest.php on line: 55
        source: \Rekalogika\Mapper\Tests\Fixtures\Adder\Comment::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\AdderDto\CommentDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/AdderTest.php on line: 103
        source: \Rekalogika\Mapper\Tests\Fixtures\Adder\ImmutablePost::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\AdderDto\ImmutablePostDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/AdderTest.php on line: 73
        source: \Rekalogika\Mapper\Tests\Fixtures\Adder\Post::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\AdderDto\PostDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line: 335
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithArrayProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayAccessPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line: 348
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithArrayProperty::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on lines: 306, 390
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithTraversableProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayAccessPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line: 320
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithTraversableProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayPropertyDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line: 433
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithTraversableProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithArrayWithGetterNoSetterDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/TraversableToArrayAccessMappingTest.php on line: 407
        source: \Rekalogika\Mapper\Tests\Fixtures\ArrayLike\ObjectWithTraversableProperties::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ArrayLikeDto\ObjectWithCollectionWithGetterNoSetterDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/BasicMappingTest.php on line: 74
        source: \Rekalogika\Mapper\Tests\Fixtures\Basic\PersonWithDogDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Basic\PersonWithDog::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/BasicMappingTest.php on line: 99
        source: \Rekalogika\Mapper\Tests\Fixtures\Basic\PersonWithDogDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Basic\PersonWithImmutableDogWithoutSetter::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DateTimeMappingTest.php on line: 112
        source: \Rekalogika\Mapper\Tests\Fixtures\DateTime\OldObjectWithDateTime::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\DateTime\OldObjectWithDateTimeDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MapPropertyPathTest.php on line: 297
        source: \Rekalogika\Mapper\Tests\Fixtures\MapPropertyPathDto\BookDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MapPropertyPath\Book::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/MethodMapperTest.php on line: 91
        source: \Rekalogika\Mapper\Tests\Fixtures\MethodMapper\ObjectWithObjectWithScalarPropertiesDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\MethodMapper\ObjectWithObjectWithScalarProperties::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectMapperTest.php on line: 155
        source: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\Baz::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectMapper\Foo::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectWithExistingValueTest.php on line: 52
        source: \Rekalogika\Mapper\Tests\Fixtures\ObjectWithExistingValueDto\RootObjectDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectWithExistingValue\RootObject::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/ObjectWithExistingValueTest.php on line: 68
        source: \Rekalogika\Mapper\Tests\Fixtures\ObjectWithExistingValueDto\RootObjectWithoutSetterDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\ObjectWithExistingValue\RootObject::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/PropertyInSetterAndConstructorTest.php on line: 45
        source: \Rekalogika\Mapper\Tests\Fixtures\PropertyInSetterAndConstructor\ParentObjectDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\PropertyInSetterAndConstructor\ParentObject::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/PropertyMappingTest.php on line: 271
        source: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\ObjectWithChild1::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/PropertyMappingTest.php on line: 284
        source: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\ObjectWithChild2::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/PropertyMappingTest.php on line: 297
        source: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\SomeObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\PropertyMapper\SomeObjectWithDateTimeImmutableDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line: 148
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithAdderRemover::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line: 195
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithAdderRemoverWithAllowDeleteAttachedToGetter::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line: 217
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithAdderRemoverWithAllowDeleteAttachedToRemover::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line: 80
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArray::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line: 124
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayWithoutAllowDeleteAttribute::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line: 171
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDto::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithImmutableAdderRemover::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line: 239
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDtoWithAllowTargetDeleteAttribute::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithAdderRemover::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line: 102
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDtoWithAllowTargetDeleteAttribute::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArray::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/RemoveTest.php on line: 261
        source: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithArrayDtoWithAllowTargetDeleteAttributeAttachedToGetter::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\Remove\ObjectWithAdderRemover::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/WitherMethodTest.php on line: 35
        source: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObjectWithObjectWithFluentSetter::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/WitherMethodTest.php on line: 71
        source: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObjectWithObjectWithImmutableSetter::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/WitherMethodTest.php on line: 59
        source: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObjectWithObjectWithSetterReturningForeignObject::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/WitherMethodTest.php on line: 47
        source: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObjectWithObjectWithVoidSetter::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/WitherMethodTest.php on line: 83
        source: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObjectWithObjectWithWither::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/WitherMethodTest.php on line: 95
        source: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObject::class,
        target: \Rekalogika\Mapper\Tests\Fixtures\WitherMethod\ParentObjectWithoutSetterDto::class
    );
    
    $mappingCollection->addObjectMapping(
        // tests/src/IntegrationTest/DynamicPropertyTest.php on lines: 277, 290
        source: \stdClass::class,
        target: \stdClass::class
    );
};